# File: roles/postgresql/tasks/packages.yml
---
- name: 'Install locales-all'
  apt:
    pkg: 'locales-all'
    state: present
  tags:
    - packages

- name: 'Install PostgreSQL'
  apt:
    pkg: "{{item}}"
    state: present
  with_items: packages_postgresql
  tags:
    - packages
