# File: roles/uwsgi/tasks/configs.yml
---
- name: 'Create uwsgi template'
  template:
    src: "{{ item.tmpl_uwsgi | default('lamp') }}.j2"
    dest: "/etc/uwsgi/apps-available/{{ item.name }}.ini"
  when: item.tmpl_uwsgi is defined
  with_items: all_websites
  notify:
    - Reload uwsgi
  tags:
    - uwsgi

- name: 'Create uwsgi symlink'
  file:
    state: "{{ item.state | default('link') }}"
    path: "/etc/uwsgi/apps-enabled/{{ item.name }}.ini"
    src: "../apps-available/{{ item.name }}.ini"
  when: item.tmpl_uwsgi is defined
  with_items: all_websites
  notify:
    - Reload uwsgi
  tags:
    - uwsgi

- name: 'Create uwsgi log directory'
  file:
    state: directory
    path: "/var/log/uwsgi/app/{{ item.name }}"
    owner: "{{ item.user }}"
    group: 'adm'
    mode: 0750
  when: item.tmpl_uwsgi is defined
  with_items: all_websites
  tags:
    - uwsgi
