# File: roles/uwsgi/tasks/packages.yml
---
- name: 'Install packages for uwsgi'
  apt:
    pkg: "{{ item }}"
    state: present
    install_recommends: No
  with_items: "{{ packages_uwsgi }}"
  retries: 3
  delay: 10
  until: apt_result|success
  register: apt_result
  tags:
    - packages
