# File: roles/apache/tasks/apache_websites.yml
---
- name: 'Create Apache template for Nginx+Apache website'
  template:
    src: "apache/{{ item.value.tmpl_apache }}.j2"
    dest: "/etc/apache2/sites-available/{{ item.key }}.conf"
  when: item.value.tmpl_apache is defined
  with_dict: "{{ all_websites }}"
  notify:
    - Reload apache
  tags:
    - configuration
    - apache

- name: 'Create Apache symlink for Nginx+Apache website'
  file:
    state: "{{ item.value.state | default('link') }}"
    path: "/etc/apache2/sites-enabled/{{ item.key }}.conf"
    src: "../sites-available/{{ item.key }}.conf"
  when: item.value.tmpl_apache is defined
  with_dict: "{{ all_websites }}"
  notify:
    - Reload apache
  tags:
    - configuration
    - apache

- name: 'Create Apache log directory for Nginx+Apache website'
  file:
    state: directory
    path: "/var/log/apache2/{{ item.key }}"
    owner: "{{ item.value.user }}"
    group: 'adm'
    mode: 0750
  when: item.value.tmpl_apache is defined
  with_dict: "{{ all_websites }}"
  tags:
    - apache
