# File: roles/websites_common/tasks/users_groups.yml
---
- name: 'Grab the user list'
  shell: "cut -d: -f1 /etc/passwd"
  changed_when: False
  always_run: yes
  register: passwd

- name: 'Create directory {{ web_home_path }}'
  file:
    state: directory
    path: "{{ web_home_path }}"
    owner: 'root'
    group: 'root'
    mode: 0755

- name: 'Create group account for Nginx+Apache website'
  group:
    state: present
    name: "{{ item.user }}"
  with_items: all_websites

- name: 'Create user account for Nginx+Apache website'
  user:
    state: present
    name: "{{ item.user }}"
    group: "{{ item.user }}"
    home: "{{ web_home_path }}/{{ item.user }}"
    move_home: no
    comment: "{{ item.name }}"
  when: item.user not in passwd.stdout_lines
  with_items: all_websites

- name: 'Create user directory www for Nginx+Apache website'
  file:
    state: directory
    path: "{{ web_home_path }}/{{ item.user }}/www"
    owner: "{{ item.user }}"
    group: 'www-data'
    mode: 0750
  with_items: all_websites
