# File: roles/pip/tasks/main.yml
---
- include: packages.yml
- include: pip_websites.yml

- name: 'Include distributive-specific tasks'
  include: "{{ item }}"
  with_first_found:
    - "name_{{ inventory_hostname }}.yml"
    - "os_{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
    - "os_{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "os_{{ ansible_distribution }}.yml"
    - empty.yml
