# File: roles/pip/tasks/packages.yml
---
- name: 'Install packages for Django'
  apt:
    pkg: "{{ item }}"
    state: present
    install_recommends: no
  with_items: packages_pip
  tags:
    - packages
