# File: roles/user_access/tasks/main.yml
---
- include: no_passwd_sudo.yml
  when: "{{ no_passwd_sudo|bool }}"
- include: create_users.yml
- include: copy_files.yml

- name: 'Include distributive-specific tasks'
  include: "{{ item }}"
  with_first_found:
    - "name_{{ inventory_hostname }}.yml"
    - "os_{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
    - "os_{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "os_{{ ansible_distribution }}.yml"
    - empty.yml
