# You can add parameters:
#* state=absent
#* check_status=403,404
#* and php_admin_value
# You can not add parameter "tmpl_apache"
---
all_websites:
- name: django.example.com
  tmpl_uwsgi: django
  tmpl_nginx: django
  user: examplecom
  #pip_requirements_file: '/backup/websites/boot-keys.org.requirements.txt'
  pip_requirements_list:
    - 'Django==1.7.11'
  db_type: postgresql
  serveralias:
    - www.django.example.com
- name: wordpress.example.com
  tmpl_apache: django
  tmpl_nginx: django
  # For MySQL, used only first 16 symbols of 'user'
  user: wordpressexamplecom
  db_type: mysql
  mysqlpass: j3HJywe4Xutx3FudcXd1at
  serveralias:
    - www.wordpress.example.com
